# ===================================================================
# Sample Spring Cloud Config.
# ===================================================================

# Property used on app startup to check the config server status
configserver:
    name: Registry config server
    status: Connected to the Registry config server

# Default JWT secret token (to be changed in production!)
gateway:
    security:
        authentication:
            jwt:
                secret: bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl
